apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-analysis
  template:
    metadata:
      labels:
        app: prom-analysis
        app.kubernetes.io/name: prom-analysis
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: prom-analysis
        app.kubernetes.io/version: 0.0.5
        app.kubernetes.io/build-version: "0.0.5"
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
        #metrics.dynatrace.com/scrape: 'true'
        #metrics.dynatrace.com/path: '/metrics'
        #metrics.dynatrace.com/port: '3000'
        #metrics.dynatrace.com/secure: 'false'
        #metrics.dynatrace.com/filter: |
        #  {
        #    "mode": "include",
        #    "names": [
        #        "tiendapc_nodejs_active_handles"
        #        ]
        #  }
    spec:
      containers:
        - name: prom-analysis
          image: mnroman/prom-analysis
          ports:
            - containerPort: 5000
          env:
          - name: DT_CUSTOM_PROP
            value: "buildVersion=0.0.1"
          - name: "DT_RELEASE_VERSION"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/version']
          - name: "DT_RELEASE_PRODUCT"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/part-of']
          - name: "DT_BUILD_VERSION"
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/build-version']

          imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
